In [6]:
import pandas as pd
import pickle as pk
import numpy as np
import math,time
from sklearn.cluster import KMeans
from sklearn import datasets
import matplotlib.pyplot as plt
data = pd.read_pickle("ptt_stock.pickle")
dic = pd.read_pickle("new//dictionary2.pickle")
N = 2445
T = 31983

In [78]:
iris=datasets.load_iris()
X=iris.data
X=X[:,2:4]
#print(X)
KM=KMeans(n_clusters=8,init='random',random_state=10)
KM.fit(docvec)
r = KM.predict(docvec)
print(list(r))

[3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 1, 3, 3, 3, 1, 3, 3, 3, 3, 3, 3, 3, 3, 2, 3, 3, 3, 6, 3, 3, 2, 3, 3, 3, 3, 3, 3, 3, 6, 3, 3, 1, 3, 3, 4, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 3, 3, 3, 2, 3, 4, 3, 3, 3, 3, 3, 3, 6, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 4, 3, 3, 3, 2, 1, 4, 6, 3, 2, 3, 3, 3, 3, 3, 4, 3, 3, 3, 3, 3, 1, 4, 3, 1, 2, 3, 3, 3, 2, 1, 3, 2, 3, 4, 3, 2, 3, 2, 3, 2, 3, 6, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 3, 3, 3, 3, 6, 3, 3, 3, 3, 2, 3, 3, 6, 3, 3, 3, 3, 3, 7, 3, 3, 3, 3, 3, 3, 6, 3, 3, 3, 3, 3, 3, 2, 3, 2, 6, 3, 4, 2, 3, 2, 3, 3, 4, 3, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 3, 3, 3, 3, 3, 2, 2, 3, 2, 3, 3, 3, 2, 3, 3, 2, 4, 0, 3, 2, 3, 2, 3, 1, 3, 3, 4, 4, 6, 3, 2, 3, 3, 3, 3, 3, 3, 3, 4, 1, 2, 3, 2, 3, 3, 1, 2, 3, 4, 3, 2, 3, 6, 3, 4, 3, 3, 6, 3, 3, 3, 4, 2, 3, 3, 2, 2, 3, 3, 4, 2, 3, 3, 1, 2, 3, 3, 3, 3, 3, 3, 1, 4, 2, 3, 4, 3, 4, 1, 3, 3, 1, 3, 4, 3, 1, 3, 3, 4, 2, 3, 4, 3, 3, 3, 2, 3, 3, 3, 6, 6, 3, 4, 3, 3, 3, 3, 3, 3, 3, 3, 2, 6, 1, 2, 3, 3, 3, 3, 4, 3, 3, 2, 

In [11]:
docvec = np.array([[0]*(T+1)])  
for i in range(N):
    v = np.zeros(T+1)  
    l = len(doclist[i])
    for j in range(l):
        data = doclist[i].iloc[j]
        tfidf = float(data[4])
        index = int(data[2])
        v[index] = tfidf
        #print(index,tfidf)
    docvec = np.append(docvec,[v],axis = 0)  
    print(i)
docvec = np.delete(docvec,0,axis = 0)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
27

1861
1862
1863
1864
1865
1866
1867
1868
1869
1870
1871
1872
1873
1874
1875
1876
1877
1878
1879
1880
1881
1882
1883
1884
1885
1886
1887
1888
1889
1890
1891
1892
1893
1894
1895
1896
1897
1898
1899
1900
1901
1902
1903
1904
1905
1906
1907
1908
1909
1910
1911
1912
1913
1914
1915
1916
1917
1918
1919
1920
1921
1922
1923
1924
1925
1926
1927
1928
1929
1930
1931
1932
1933
1934
1935
1936
1937
1938
1939
1940
1941
1942
1943
1944
1945
1946
1947
1948
1949
1950
1951
1952
1953
1954
1955
1956
1957
1958
1959
1960
1961
1962
1963
1964
1965
1966
1967
1968
1969
1970
1971
1972
1973
1974
1975
1976
1977
1978
1979
1980
1981
1982
1983
1984
1985
1986
1987
1988
1989
1990
1991
1992
1993
1994
1995
1996
1997
1998
1999
2000
2001
2002
2003
2004
2005
2006
2007
2008
2009
2010
2011
2012
2013
2014
2015
2016
2017
2018
2019
2020
2021
2022
2023
2024
2025
2026
2027
2028
2029
2030
2031
2032
2033
2034
2035
2036
2037
2038
2039
2040
2041
2042
2043
2044
2045
2046
2047
2048
2049
2050
2051
2052
2053
2054
2055
2056
2057
2058
2059
2060


In [265]:
#docvec = np.delete(docvec,0,axis = 0)
print(docvec.shape)
print(X.shape)
print(docvec)
sum(docvec[0])

(1683, 147239)
(150, 2)
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


5.814903037475998

In [91]:
KM=KMeans(n_clusters=8,init='random',random_state=10)
KM.fit(docvec)
r = KM.predict(docvec)
print(list(r))

[3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 1, 3, 3, 3, 1, 3, 3, 3, 3, 3, 3, 3, 3, 2, 3, 3, 3, 6, 3, 3, 2, 3, 3, 3, 3, 3, 3, 3, 6, 3, 3, 1, 3, 3, 4, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 3, 3, 3, 2, 3, 4, 3, 3, 3, 3, 3, 3, 6, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 4, 3, 3, 3, 2, 1, 4, 6, 3, 2, 3, 3, 3, 3, 3, 4, 3, 3, 3, 3, 3, 1, 4, 3, 1, 2, 3, 3, 3, 2, 1, 3, 2, 3, 4, 3, 2, 3, 2, 3, 2, 3, 6, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 3, 3, 3, 3, 6, 3, 3, 3, 3, 2, 3, 3, 6, 3, 3, 3, 3, 3, 7, 3, 3, 3, 3, 3, 3, 6, 3, 3, 3, 3, 3, 3, 2, 3, 2, 6, 3, 4, 2, 3, 2, 3, 3, 4, 3, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 3, 3, 3, 3, 3, 2, 2, 3, 2, 3, 3, 3, 2, 3, 3, 2, 4, 0, 3, 2, 3, 2, 3, 1, 3, 3, 4, 4, 6, 3, 2, 3, 3, 3, 3, 3, 3, 3, 4, 1, 2, 3, 2, 3, 3, 1, 2, 3, 4, 3, 2, 3, 6, 3, 4, 3, 3, 6, 3, 3, 3, 4, 2, 3, 3, 2, 2, 3, 3, 4, 2, 3, 3, 1, 2, 3, 3, 3, 3, 3, 3, 1, 4, 2, 3, 4, 3, 4, 1, 3, 3, 1, 3, 4, 3, 1, 3, 3, 4, 2, 3, 4, 3, 3, 3, 2, 3, 3, 3, 6, 6, 3, 4, 3, 3, 3, 3, 3, 3, 3, 3, 2, 6, 1, 2, 3, 3, 3, 3, 4, 3, 3, 2, 

In [101]:
x = []
temp = list()
for i in range(8):
    x.append(temp.copy())
for i in range(len(r)):
    x[r[i]].append(i)
print(x)

[[217, 350, 444, 482, 616, 681, 697, 801, 808, 861, 899, 936, 994], [10, 14, 41, 88, 104, 107, 113, 223, 239, 245, 273, 281, 288, 291, 295, 323, 337, 370, 377, 401, 406, 430, 434, 449, 514, 574, 578, 593, 604, 642, 662, 665, 671, 680, 773, 785, 811, 817, 820, 832, 867, 891, 895, 903, 911, 942, 947, 954, 956, 957, 966, 972, 973, 976], [23, 30, 56, 60, 82, 87, 92, 108, 112, 115, 119, 121, 123, 137, 147, 170, 172, 176, 178, 183, 199, 205, 206, 208, 212, 215, 219, 221, 230, 240, 242, 246, 250, 262, 265, 266, 270, 274, 283, 299, 305, 321, 324, 332, 334, 336, 341, 342, 348, 351, 352, 354, 357, 364, 378, 381, 382, 387, 389, 390, 392, 396, 399, 413, 416, 420, 421, 422, 445, 446, 450, 454, 459, 460, 462, 481, 486, 488, 499, 506, 512, 516, 528, 541, 565, 567, 572, 580, 590, 600, 602, 603, 610, 611, 615, 621, 626, 643, 646, 678, 684, 700, 702, 709, 710, 711, 725, 728, 742, 743, 748, 759, 774, 776, 777, 787, 788, 792, 796, 807, 818, 819, 822, 830, 833, 835, 844, 847, 853, 859, 860, 863, 868, 873, 

In [252]:
x2 = [] #term -> class -> (x2score,pre_on,pre_off,ab_on,ab_off)
x2class = []
temp = list()
for j in range(len(x)): #for each class
    x2class.append(temp.copy())
    
for i in range(100): #for each term
    x2.append(temp.copy())
    index = dic.t_index[i]
    post = dic.posting[i]
    print(index,post)
    for j in range(len(x)): #for each class
        x2[i].append(temp.copy())
        scores = []
        pre_on = 0
        pre_off = 0
        ab_on = 0
        ab_of = 0
        for k in range(len(x[j])): #for each doc
            if x[j][k] in post: #if apperance
                pre_on += 1
        pre_off = len(post) - pre_on
        ab_on = len(x[j]) - pre_on
        ab_off = N - pre_on - pre_off - ab_on
        scores = [pre_on,pre_off,ab_on,ab_off]
        print(scores)
        
        pre = pre_on + pre_off
        ab = ab_on + ab_off
        on = pre_on + ab_on
        off = pre_off + ab_off
        
        Epre_on = pre * on / N
        Epre_off = pre * off / N
        Eab_on = ab * on / N
        Eab_off = ab * off / N
        
        x2score = 0
        x2score += pow((pre_on - Epre_on),2)/Epre_on
        x2score += pow((pre_off - Epre_off),2)/Epre_off
        x2score += pow((ab_on - Eab_on),2)/Eab_on
        x2score += pow((ab_off - Eab_off),2)/Eab_off
        
        x2[i][j] = [x2score,pre_on,pre_off,ab_on,ab_off]
        x2class[j].append([index,x2score])
    print("=====")
print(len(x2)) 
print("=====")
print(len(x2class)) 
print("=====")

for i in range(8):
    print(x2class[i])
    x2class[i] = sorted(x2class[i],key = lambda x : x[1],reverse = True)
    print(x2class[i])
    print("=====")
for i in range(8):
    for j in range(10):
        print(x2class[i][j])
    print("=====")

1 [6329, 9305, 10836, 10922, 22386, 25354, 26885, 26971]
[0, 8, 13, 31411]
[0, 8, 54, 31370]
[0, 8, 155, 31269]
[0, 8, 663, 30761]
[0, 8, 79, 31345]
[0, 8, 2, 31422]
[0, 8, 34, 31390]
[0, 8, 1, 31423]
=====
2 [7888, 23951]
[0, 2, 13, 31417]
[0, 2, 54, 31376]
[0, 2, 155, 31275]
[0, 2, 663, 30767]
[0, 2, 79, 31351]
[0, 2, 2, 31428]
[0, 2, 34, 31396]
[0, 2, 1, 31429]
=====
3 [9003, 25052]
[0, 2, 13, 31417]
[0, 2, 54, 31376]
[0, 2, 155, 31275]
[0, 2, 663, 30767]
[0, 2, 79, 31351]
[0, 2, 2, 31428]
[0, 2, 34, 31396]
[0, 2, 1, 31429]
=====
4 [1906, 4266, 6533, 20323, 22590]
[0, 5, 13, 31414]
[0, 5, 54, 31373]
[0, 5, 155, 31272]
[0, 5, 663, 30764]
[0, 5, 79, 31348]
[0, 5, 2, 31425]
[0, 5, 34, 31393]
[0, 5, 1, 31426]
=====
5 [1901, 4266, 20323]
[0, 3, 13, 31416]
[0, 3, 54, 31375]
[0, 3, 155, 31274]
[0, 3, 663, 30766]
[0, 3, 79, 31350]
[0, 3, 2, 31427]
[0, 3, 34, 31395]
[0, 3, 1, 31428]
=====
6 [1274]
[0, 1, 13, 31418]
[0, 1, 54, 31377]
[0, 1, 155, 31276]
[0, 1, 663, 30768]
[0, 1, 79, 31352]
[0,

In [26]:
def calculatex2(x,dic):
    T = 31983
    x2 = [] #term -> class -> (x2score,pre_on,pre_off,ab_on,ab_off)
    x2class = []
    temp = list()
    for j in range(len(x)): #for each class
        x2class.append(temp.copy())

    for i in range(T): #for each term
        x2.append(temp.copy())
        index = dic.t_index[i]
        post = dic.posting[i]
        #print(index,post)
        for j in range(len(x)): #for each class
            x2[i].append(temp.copy())
            scores = []
            pre_on = 0
            pre_off = 0
            ab_on = 0
            ab_of = 0
            for k in range(len(x[j])): #for each doc
                if x[j][k] in post: #if apperance
                    pre_on += 1
            pre_off = len(post) - pre_on
            ab_on = len(x[j]) - pre_on
            ab_off = N - pre_on - pre_off - ab_on
            scores = [pre_on,pre_off,ab_on,ab_off]
            #print(scores)

            pre = pre_on + pre_off
            ab = ab_on + ab_off
            on = pre_on + ab_on
            off = pre_off + ab_off

            Epre_on = pre * on / N
            Epre_off = pre * off / N
            Eab_on = ab * on / N
            Eab_off = ab * off / N

            x2score = 0
            x2score += pow((pre_on - Epre_on),2)/Epre_on
            x2score += pow((pre_off - Epre_off),2)/Epre_off
            x2score += pow((ab_on - Eab_on),2)/Eab_on
            x2score += pow((ab_off - Eab_off),2)/Eab_off

            x2[i][j] = [x2score,pre_on,pre_off,ab_on,ab_off]
            x2class[j].append([index,x2score])
    return x2,x2class

In [59]:
def sortclass(x2class,tokenN):
    c = []
    temp = []
    for i in range(len(x2class)):
        c.append(temp.copy())
        x2class[i] = sorted(x2class[i],key = lambda x : x[1],reverse = True)
    for i in range(len(x2class)):
        for j in range(tokenN):
            c[i].append(x2class[i][j])
    return c

In [64]:
def KM(docvec):
    KM=KMeans(n_clusters=14,init='random',random_state=10)
    KM.fit(docvec)
    r = list(KM.predict(docvec))
    x = []
    temp = list()
    for i in range(14):
        x.append(temp.copy())
    for i in range(len(r)):
        x[r[i]].append(i)
    return x

In [ ]:
a = KM(docvec)

In [ ]:
for x in a:
    print(len(x))

In [62]:
x2,x2class = calculatex2(a,dic)
r = sortclass(x2class,50)

In [63]:
for i in range(len(r)):
    for j in range(len(r[i])):
        print(dic.iloc[r[i][j][0]].term)
    print("=====")

今天日
公司價
今年季
漲停價
跳空推嘎上去
收盤價
大盤價
拉回來
台灣中油公司
明安
跌停價
昨日
上車人
僮華安穩懋
開盤價
去年年
當天人
成長價
主力人
產品商
投資人
需求主
短線客
伴隨
點位元
開高收低
區間元
讀版
股利主
盤整下
跌破元
量縮價
現金主
中國中
華安人
均衡
疫情主
主見
停擺
早安同泰
謝謝來
營收元
支撐住
壓力區
處置備
訂單案
業務量
市場值
營運動
缺口元
=====
賭博式
器械指
辜仲瑩
中籤
中長多
人們
倒好多
分鐘
到日
副反應
外話
幹閉
張頎邦
形然
懶得
房產者
手上
採購案
放在
救市
棉價
沒什麼
百分點
端看
端遊
網拍
老鼠會
股杏國
菜市場
裕民
陌生
雙率
高要
備註
光寶科
入金
單不要
快不會
窮人
開張
中實戶
中聯資
五檔
以來
休假
入土
八千
出頭
分析圖
列標
=====
今天日
公司價
突破億
跌破元
收盤價
大盤價
拉回來
外資期
投信想
月線人
台積電主
開盤價
法人人
震盪盤
區間元
漲停價
整理價
明安
股利主
籌碼型
合作案
日線值
短線客
隔日沖
停利價
台灣中油公司
跳空推嘎上去
進場人
高點人
出貨台
昨日
出場價
操作員
反彈到
公開法
回測到
技順
今日券
政府心
引述型
散戶人
早盤度
來源年
盤整下
企業會
例子
帶量上
現金主
買超多
高檔化
=====
特斯拉功
電池公司
台銀
電池組
續航力
馬斯克甲
特斯拉股東
車企
閉閉
蔚來事
流通性
阿虛之銘
換電站
二手車車商
卦張
單都
寧轉
底目
張兆豐金
特斯拉蔚
特斯拉順
皆知
租用費
秦力洪蔚
蔚來日
蔚藍
財力會
送審
透出
溢價
電話線
交織布
電動車人
截二
成交值
細胞
加碼點
李斌蔚
游刃餘
請假
走元
里程碑
車尾燈
二話
保障
信小之銘言
嘎推急
回篇
埃克森
報載
=====
營收元
成長價
年增倍
訂單案
增加點
去年年
產品商
需求主
毛利理
發文日
表現出
應用主
簡直
水溫
細分
新高三
受惠於
可望於
投資股
客戶單
今年季
買超多
法人人
屯滿又
股價元
退場元
基本面月
刪減
業績股
珍藏
毛利利
維持率
純熟
回溫由田
長期元
分類心
審查
利益股
盈餘元
機制元
月增率
比點
伺機
營業員
營運動
停損不錯
創出量
打出
忌日
預期價
=====
台積電主
台積

In [34]:
dic.iloc[1621]

t_index                                                 1622
term                                                      今天
df                                                       929
posting    [2, 4, 5, 9, 10, 11, 12, 13, 15, 17, 19, 22, 2...
Name: 1621, dtype: object

In [10]:
data

author                                  title  \
0            louis960126 (JLingogo)                          Re: [標的] 鴻海 多   
1            Arizona989 (心平氣和，和氣生財)           [新聞] 氣候變遷題材發酵 美銀看好銅價突破10,000   
2                  justicide (有話直說)  Re: [標的] 美股 AMCX (AMC Networks) 不是AMC   
3                 homura456 (股市反指標)               [新聞] 不只台股 期貨小白去年也大增 期交所罕   
4                     MiniArse (型男)                Re: [標的]：美國石油公司  OXY.US   
...                             ...                                    ...   
31427           clubbox (史上最強7788 )                       Re: [標的] 2884玉山金   
31428       elfish123 (該教一下外勞什麼叫家教)           Re: [新聞] 救台股放大絕 國安基金五千億最快明天進   
31429          shala (沙羅是轉換後的文字檔打m)                              [標的] 台指 空   
31430                 asusqq (Paul)       [標的] 美孚石油Exxon Mobil Corporation   
31431  MacBookAir12 (New Mac Water)           Re: [新聞] 救台股放大絕 國安基金五千億最快明天進   

                           time  \
0      Thu Jan 14 22:48:05 2021   
1      Thu Jan 14 22:56:51 2021   
2      Thu Jan 14 23:03:59 2021   
3      Thu Jan 14 23:12:41 2021   
4      Thu Jan 14 23:28:28 2021   
...                         ...   
31427  Thu Mar 19 19:41:14 2020   
31428  Thu Mar 19 19:43:41 2020   
31429  Thu Mar 19 19:44:07 2020   
31430  Thu Mar 19 19:46:31 2020   
31431  Thu Mar 19 19:56:36 2020   

                                                 content  \
0      https://i.imgur.com/dGgzk3w.jpg\n去年四月的時候用博士獎學金...   
1      \n1.原文連結：\n\nhttps://reurl.cc/3NDGEj\n\n2.原文內容...   
2      從站上30元那天初次PO文至今，AMCX來到了4X元。想必大家也開始考慮是否該獲利了結。\n...   
3                                                      0   
4          來到 24.x 囉...\n\n    WTI 西德洲原油期貨已經差不多回到去年 1...   
...                                                  ...   
31427  ※ 引述《clubbox (史上最強7788 )》之銘言：\n: 1. 標的：2884玉山金...   
31428  \n有夠垃圾的報導內容\n\n5000億是國安基金的總值，你以為他跟鄉民一樣\n\n一次al...   
31429  1. 標的：台指\n\n2. 分類：空\n\n3. 分析/正文：\n\n政府軍今日誓師，大將...   
31430  \n1. 標的：美孚石油\n\n2. 分類：多\n\n3. 分析/正文：\n\nhttps:...   
31431  可以回顧2015六月開始的文章，\n其實跟現有點接近，\n甚至「煎熬」的改編，之前也有出現過...   

                                                     url  \
0      https://www.ptt.cc/bbs/Stock/M.1610635687.A.5D...   
1      https://www.ptt.cc/bbs/Stock/M.1610636213.A.1B...   
2      https://www.ptt.cc/bbs/Stock/M.1610636643.A.CB...   
3      https://www.ptt.cc/bbs/Stock/M.1610637164.A.B7...   
4      https://www.ptt.cc/bbs/Stock/M.1610638110.A.21...   
...                                                  ...   
31427  https://www.ptt.cc/bbs/Stock/M.1584618075.A.9A...   
31428  https://www.ptt.cc/bbs/Stock/M.1584618223.A.C4...   
31429  https://www.ptt.cc/bbs/Stock/M.1584618250.A.32...   
31430  https://www.ptt.cc/bbs/Stock/M.1584618393.A.F7...   
31431  https://www.ptt.cc/bbs/Stock/M.1584618998.A.8A...   

                                                  tokens  
0      [去年, 四月, 時候, 博士, 獎學金, 梭哈鴻海, 原本, 考慮, 出半, 看到, 外資...  
1      [原文, 連結, 原文, 內容, 氣候, 變遷, 題材, 發酵, 美銀, 看好, 銅價, 突...  
2      [站上, 那, 初次文, 至今, 來到, 元想必, 大家, 開始, 考慮, 該, 獲利, 以...  
3                                                     []  
4      [來到, 西德洲, 原油, 期貨, 已經, 差不多, 回到, 去年, 月底, 水準, 當時,...  
...                                                  ...  
31427  [引述, 上, 強, 銘言標, 玉山金, 分類, 分析, 正文, 基本面, 八, 成長, 殖...  
31428  [垃圾, 報導, 內容, 國安, 基金, 總值, 以, 跟, 鄉民, 樣次, 之前, 億花,...  
31429  [標台, 分類空, 分析, 正文, 政府軍, 今日, 誓師, 大將, 知, 不過, 重要, ...  
31430  [標美孚, 石油, 分類, 分析, 正文, 接近, 低點, 可以, 低接, 退場, 機制, ...  
31431  [可以, 回顧, 六月, 開始, 文章, 其實, 現點, 接近, 甚至, 煎熬, 改編, 之...  

[31432 rows x 6 columns]

In [9]:
dic

t_index term df                                  posting
0            1   丁丁  2                              [795, 1260]
1            2   丁二  1                                    [272]
2            3  丁二烯  1                                    [270]
3            4  七傷拳  1                                   [2166]
4            5   七八  7  [706, 712, 849, 1374, 1961, 2239, 2324]
...        ...  ... ..                                      ...
31978    31979  龐大千  1                                   [1300]
31979    31980   龜密  3                            [89, 92, 119]
31980    31981   龜山  1                                    [879]
31981    31982   龜毛  1                                    [329]
31982    31983   龜笑  2                             [1026, 1031]

[31983 rows x 4 columns]

In [ ]:
dic[dic.loc[:,'term'] == "丁丁"]

In [68]:
# Add idf
loglist = []
for x in dic.df:
    log = math.log(N*x,10)
    loglist.append(log)
#print(loglist)
dic["idf"] = loglist

In [4]:
%%script C:\Users\User\AppData\Local\Programs\Python\Python38\python.exe
N = 2445
import sys
import pickle as pk
print(sys.version)

doclist = []
for i in range(N):
    d = open('new//tfidf_f//%d.pkl'%i, 'rb')
    f = pk.load(d)
    f.to_pickle('new//tfidf_f2//%d.pkl'%i, protocol=4)

3.8.3 (tags/v3.8.3:6f8c832, May 13 2020, 22:37:02) [MSC v.1924 64 bit (AMD64)]


In [7]:
doclist = []
for i in range(N):
    d = open('new//tfidf_f2//%d.pkl'%i, 'rb')
    f = pk.load(d)
    doclist.append(f)

In [17]:
doclist[2000]

term  tf  t_index   df    tf-idf
109    上漲   1      225  207  0.022177
66   上漲下跌   1      226    1  0.070076
143    上網   1      256    9  0.050341
82     下跌   5      423  182  0.116668
173   不只要   1      518    1  0.070076
..    ...  ..      ...  ...       ...
88     非常   1    30701  212  0.021963
115    題材   1    31034  138  0.025819
112    類股   2    31070   81  0.061210
79     高點   2    31630  305  0.037392
1     黑犀牛   1    31821    3  0.060208

[184 rows x 5 columns]

In [274]:
doclist[1].iloc[2]

term              今年
tf                 1
t_index         7579
df              8334
tf-idf     0.0209326
Name: 62, dtype: object